nelmio_api_doc:
    documentation:
        info:
            title: onlineShop
            description: Application d'achat de vétement en ligne !
            version: 1.0.0
        
        paths:
            /api/login_check:
                post:
                    operationId: postCredentialsItem
                    tags:
                        - Token
                    summary: Permet d'obtenir le token JWT pour se logger.
                    requestBody:
                        description: Crée un nouveau token JWT
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Credentials'
                    responses:
                        '200':
                            description: Récupère le token JWT
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'

        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: test@test.com
                        password:
                            type: string
                            default: 0123456789
                CommandDetail:
                    type: object
                    properties: 
                        id:
                            type: integer
                            example: 1
                        status: 
                            type: string
                            example: En cours de préparation
                        user:
                            $ref: '#/components/schemas/UserDetail'
                        total_price:
                            type: string
                            example: "39.98"
                        date:
                            type: string
                            format: date-time
                            example: "2023-11-13T12:34:56Z"
                        products:
                            type: array
                            items: 
                                $ref: '#/components/schemas/ProductDetail'

                UserDetail:
                    type: object
                    properties:
                        id:
                            type: integer
                            example: 1
                        username:
                            type: string
                            example: test_user
                        email:
                            type: string
                            example: test@test.com

                ProductDetail:
                    type: object
                    properties:
                        id:
                            type: integer
                            example: 1
                        name:
                            type: string
                            example: Product Name
                        price:
                            type: float
                            example: 10.99
                        inventory:
                            type: integer
                            example: 100



            securitySchemes:
                bearerAuth:
                    type: apiKey
                    in: header
                    name: Authorization # or another header name
        security:
               - bearerAuth: []

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
